[package]
name = "webgpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.12.0"
async-executor = "1.0"
pollster = "0.2"
env_logger = "0.9"
bytemuck = "1.9.1"